import React from 'react';
import Chip from '@material-ui/core/Chip';
import Autocomplete from '@material-ui/lab/Autocomplete';
import { makeStyles } from '@material-ui/core/styles';
import TextField from '@material-ui/core/TextField';

const useStyles = makeStyles((theme) => ({
    root: {
        "& .MuiInputLabel-outlined:not(.MuiInputLabel-shrink)": {
            // Default transform is "translate(14px, 20px) scale(1)""
            // This lines up the label with the initial cursor position in the input
            // after changing its padding-left.
            transform: "translate(34px, 20px) scale(1);",
            color: "white",
        },
        "& .MuiInputLabel-outlined.MuiInputLabel-shrink":{
            color: "white",
        }
    },
    inputRoot: {
        color: "white",
        // This matches the specificity of the default styles at https://github.com/mui-org/material-ui/blob/v4.11.3/packages/material-ui-lab/src/Autocomplete/Autocomplete.js#L90
        '&[class*="MuiOutlinedInput-root"] .MuiAutocomplete-input:first-child': {
            // Default left padding is 6px
            paddingLeft: 26
        },
        "& .MuiOutlinedInput-notchedOutline": {
            borderColor: "white",
            padding: 20,
        },
        "&:hover .MuiOutlinedInput-notchedOutline": {
            borderColor: "orange"
        },
        "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
            borderColor: "white"
        }
    }
}));

export default function AppointmentSearchComponent(props) {
    const classes = useStyles();

    const [searchTags, setSearchTags] = React.useState([]);



    return (
        <div className={classes.root}>
            <Autocomplete
                multiple
                classes={classes}
                id="tags-outlined"
                options={allInterests}
                onChange={(event, value) => props.onChangeSearchInterests(value)}
                getOptionLabel={(option) => option}
                filterSelectedOptions
                renderInput={(params) => (
                    <TextField
                        {...params}
                        variant="outlined"
                        label="Search your interests"
                        placeholder="Search for Tags"
                    />
                )}
            />
        </div>
    );
}

// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
const allInterests = ["Business",
    "Advertising",
    "Agriculture",
    "Aviation",
    "Banking",
    "Investment",
    "Design",
    "Fashion",
    "Graphic",
    "Interior",
    "Design",
    "Economics",
    "Engineering",
    "Start-Ups",
    "Health care",
    "Education",
    "Management",
    "Marketing",
    "Nursing",
    "Online",
    "Marketing",
    "SEO",
    "Social media",
    "Web design",
    "Web devel.",
    "Finance",
    "Insurance",
    "Loans",
    "Real estate",
    "Retail",
    "Sales",
    "Science",
    "Games",
    "Gambling",
    "Online games",
    "Online poker",
    "Video games",
    "Racing games",
    "RPGs",
    "Shooter games",
    "Strategy",
    "Video games",
    "Word games",
    "Live events",
    "Ballet",
    "Bars",
    "Concerts",
    "Dancehalls",
    "Festivals",
    "Nightclubs",
    "Parties",
    "Plays",
    "Theatre",
    "Movies",
    "Animes",
    "Comedy",
    "Documentaries",
    "Fantasy",
    "Horror",
    "Musicals",
    "Theater",
    "Sci-Fi movies",
    "Thrillers",
    "Music",
    "Blues",
    "Classical",
    "Country",
    "Dance",
    "Electronic",
    "Gospel",
    "Heavy metal",
    "Hip hop",
    "Jazz music",
    "Music videos",
    "Pop music",
    "Reading",
    "Books",
    "Comics",
    "E-books",
    "Fiction books",
    "Literature",
    "Magazines",
    "Manga",
    "Mystery",
    "Newspapers",
    "Non-fiction",
    "Novels",
    "TV",
    "TV comedies",
    "Game shows",
    "Reality shows",
    "TV talkshows",
    "Family",
    "Relationships",
    "Dating",
    "Family",
    "Fatherhood",
    "Friendship",
    "Marriage",
    "Motherhood",
    "Parenting",
    "Weddings",
    "Fitness",
    "Wellness",
    "Bodybuilding",
    "Meditation",
    "Exercise",
    "Running",
    "Weight lifting",
    "Yoga",
    "Food",
    "Drinks",
    "Alcohol",
    "Beer",
    "Wine",
    "Beverages",
    "Coffee",
    "Energy drinks",
    "Juice",
    "Soft drinks",
    "Tea",
    "Cooking",
    "Baking",
    "Recipes",
    "Cuisine",
    "Chinese food",
    "French food",
    "German food",
    "Greek food",
    "Indian food",
    "Spanish cuisine",
    "Thai cuisine",
    "Barbecue",
    "Chocolate",
    "Desserts",
    "Fast food",
    "Organic food",
    "Pizza",
    "Seafood",
    "Vegan",
    "Vegetarian",
    "Paleo",
    "Keto",
    "Fasting",
    "Diners",
    "Arts",
    "Acting",
    "Crafts",
    "Dance",
    "Drawing",
    "Drums",
    "Fine art",
    "Guitar",
    "Painting",
    "Photography",
    "Sculpture",
    "Singing",
    "Writing",
    "Current events",
    "Gardening",
    "DIY",
    "Furniture",
    "Gardening",
    "Home",
    "Pets",
    "Birds",
    "Cats",
    "Dogs",
    "Fish",
    "Horses",
    "Pet food",
    "Rabbits",
    "Reptiles",
    "Law",
    "Military",
    "Politics",
    "Religion",
    "Sustainability",
    "Veterans",
    "Volunteering",
    "Travel",
    "Adventure",
    "Air travel",
    "Beaches",
    "Car rentals",
    "Cruises",
    "Ecotourism",
    "Hotels",
    "Lakes",
    "Mountains",
    "Nature",
    "Theme parks",
    "Tourism",
    "Vacations",
    "Vehicles",
    "Automobiles",
    "Boats",
    "Hybrids",
    "Minivans",
    "Motorcycles",
    "RVs",
    "SUVs",
    "Scooters",
    "Trucks",
    "Shopping",
    "Fashion",
    "Beauty",
    "Cosmetics",
    "Fragrances",
    "Hairs",
    "Spas",
    "Tattoos",
    "Clothing",
    "Shoes",
    "Dresses",
    "Handbags",
    "Jewelry",
    "Sunglasses",
    "Shopping",
    "Boutiques",
    "Coupons",
    "Toys",
    "Sports",
    "Ourdoors",
    "Boating",
    "Camping",
    "Fishing",
    "Hunting",
    "Biking",
    "Hiking",
    "Surfing",
    "Sports",
    "Football",
    "Soccer",
    "Formel 1",
    "Baseball",
    "Basketball",
    "Golf",
    "Marathons",
    "Skiing",
    "Snowboarding",
    "Swimming",
    "Tennis",
    "Thriathlons",
    "Volleyball",
    "Technology",
    "Computers",
    "Free software",
    "Hard drives",
    "Networking",
    "Software",
    "MERN",
    "Tablets",
    "Camcorders",
    "Cameras",
    "E-books",
    "GPS devices",
    "Game consoles",
    "Mobile phones",
    "Projectors",
    "Smartphones",
    "Televisions",
];
